# Generated by Django 4.2.30 on 2026-05-11 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('role', models.CharField(default='superadmin', max_length=50)),
                ('estado', models.CharField(default='ACTIVA', max_length=20)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'superadmin',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('visibilidad', models.CharField(choices=[('todos', 'Todos'), ('area', 'Área Específica'), ('persona', 'Persona Específica')], default='todos', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curso',
                'ordering': ['orden'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DatosArea',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'datos_area',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DatosCargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=100)),
                ('nivel', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'datos_cargo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DatosEmpleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('auth_id', models.UUIDField(blank=True, null=True)),
                ('correo_corporativo', models.EmailField(max_length=255, unique=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVO', 'Inactivo')], default='ACTIVA', max_length=20)),
                ('id_permisos', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Editor'), (3, 'Usuario')], default=3)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('primer_login', models.BooleanField(default=True)),
                ('datos_completados', models.BooleanField(default=False)),
                ('permitir_edicion_datos', models.BooleanField(default=False)),
                ('ultima_actividad', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, db_column='area_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.datosarea')),
                ('cargo', models.ForeignKey(blank=True, db_column='cargo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.datoscargo')),
            ],
            options={
                'db_table': 'empleado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='N8nLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('workflow_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'Exitoso'), ('ERROR', 'Error')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('destinatario', models.EmailField(blank=True, max_length=255, null=True)),
                ('tipo_evento', models.CharField(blank=True, max_length=100, null=True)),
                ('response_data', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'n8n_log',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('apodo', models.CharField(blank=True, help_text='Nombre como desea ser llamado/a', max_length=50, null=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=2)),
                ('numero_documento', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReglamentoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(blank=True, default='')),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reglamento_item',
                'ordering': ['orden'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TareasCalendario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('creado_por', models.UUIDField(blank=True, null=True)),
                ('area', models.ForeignKey(blank=True, db_column='id_area', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.datosarea')),
                ('empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.datosempleado')),
            ],
            options={
                'db_table': 'tareas_calendario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SolicitudesPassword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('atendida', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='api.datosempleado')),
            ],
            options={
                'db_table': 'solicitudes_password',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='datosempleado',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='api.persona'),
        ),
        migrations.CreateModel(
            name='DatosContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_personal', models.EmailField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('nombre_contacto_emergencia', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True)),
                ('parentesco_emergencia', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacto', to='api.persona')),
            ],
            options={
                'db_table': 'datos_contacto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CursoHistorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curso_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('accion', models.CharField(choices=[('crear', 'Curso Creado'), ('editar', 'Curso Editado'), ('eliminar', 'Curso Eliminado'), ('agregar_contenido', 'Contenido Agregado'), ('eliminar_contenido', 'Contenido Eliminado')], max_length=20)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('usuario_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='api.curso')),
            ],
            options={
                'db_table': 'curso_historial',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CursoContenido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('youtube', 'Video YouTube'), ('video', 'Video Propio'), ('documento', 'Documento'), ('texto', 'Texto/Artículo'), ('enlace', 'Enlace Externo'), ('cuestionario', 'Cuestionario')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='cursos/')),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='api.curso')),
            ],
            options={
                'db_table': 'curso_contenido',
                'ordering': ['orden'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='area',
            field=models.ForeignKey(blank=True, db_column='area_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.datosarea'),
        ),
        migrations.AddField(
            model_name='curso',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, db_column='empleado_asignado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_asignados', to='api.datosempleado'),
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('uso_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('permisos', models.JSONField(blank=True, default=dict)),
                ('ip_permitidas', models.JSONField(blank=True, default=list)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_key',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('recuperacion_password', 'Recuperación de Contraseña'), ('login_fallido', 'Intento de Login Fallido'), ('otro', 'Otro')], default='recuperacion_password', max_length=50)),
                ('email_solicitante', models.EmailField(max_length=255)),
                ('nombre_solicitante', models.CharField(blank=True, max_length=255, null=True)),
                ('rol_solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_alerta', models.CharField(choices=[('pendiente', 'Pendiente'), ('atendida', 'Atendida'), ('ignorada', 'Ignorada')], default='pendiente', max_length=50)),
                ('usuario_existe', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_atendidas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.datosempleado')),
            ],
            options={
                'db_table': 'alertas',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
    ]
