# Generated by Django 4.2.30 on 2026-06-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_acceso_formularios_sqf'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglamentoitem',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='reglamento/'),
        ),
    ]
