# Generated by Django 4.2.30 on 2026-06-12 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_permisos_sqf_por_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SugerenciaEmpleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sugerencia', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('recibida', models.BooleanField(default=False)),
                ('fecha_recibida', models.DateTimeField(blank=True, null=True)),
                ('confirmacion_vista', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='api.datosempleado')),
            ],
            options={
                'db_table': 'sugerencias_empleado',
                'ordering': ['-fecha_envio'],
                'managed': True,
                'indexes': [models.Index(fields=['recibida', 'fecha_envio'], name='sugerencia_recibida_idx'), models.Index(fields=['empleado', 'fecha_envio'], name='sugerencia_empleado_idx')],
            },
        ),
    ]
