# Generated by Django 4.2.30 on 2026-06-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_sugerenciaempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_expedicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='lugar_expedicion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
