# Generated by Django 4.2.30 on 2026-06-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_persona_add_expedicion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ciudad_nacimiento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='departamento_nacimiento',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='descripcion_discapacidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('UL', 'Unión Libre'), ('D', 'Divorciado/a'), ('V', 'Viudo/a')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='estrato_socioeconomico',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=models.CharField(blank=True, default='Colombiana', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='numero_hijos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='pais_nacimiento',
            field=models.CharField(blank=True, default='Colombia', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='tiene_discapacidad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='tiene_hijos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_vivienda',
            field=models.CharField(blank=True, choices=[('propia', 'Propia'), ('arrendada', 'Arrendada'), ('familiar', 'Familiar')], max_length=10, null=True),
        ),
    ]
