# Generated by Django 4.2.30 on 2026-06-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_persona_datos_personales_completos'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosempleado',
            name='datos_persona_completados',
            field=models.BooleanField(default=False),
        ),
    ]
