# Generated by Django 4.2.30 on 2026-06-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_datosempleado_datos_persona_completados'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='placa_vehiculo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='tiene_vehiculo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, choices=[('moto', 'Moto'), ('carro', 'Carro'), ('ambos', 'Moto y Carro')], max_length=10, null=True),
        ),
    ]
