# Generated by Django 4.2.30 on 2026-06-22 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_vehiculo_to_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosempleado',
            name='datos_academicos_completados',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DatosAcademicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_educativo', models.CharField(choices=[('bachiller', 'Bachiller'), ('tecnico', 'Técnico'), ('tecnologo', 'Tecnólogo'), ('profesional', 'Profesional'), ('especializacion', 'Especialización'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado'), ('otro', 'Otro')], max_length=20)),
                ('titulo_obtenido', models.CharField(max_length=255)),
                ('institucion', models.CharField(max_length=255)),
                ('ciudad_institucion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_graduacion', models.DateField(blank=True, null=True)),
                ('en_curso', models.BooleanField(default=False)),
                ('graduado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academicos', to='api.persona')),
            ],
            options={
                'db_table': 'datos_academicos',
                'ordering': ['-fecha_graduacion', '-fecha_inicio'],
                'managed': True,
            },
        ),
    ]
