# Generated by Django 4.2.30 on 2026-06-23 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_seed_cargos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('CAMBIO_CARGO', 'Cambio de Cargo'), ('TRASLADO', 'Traslado de Área'), ('AJUSTE_SALARIAL', 'Ajuste Salarial'), ('CAMBIO_CONTRATO', 'Cambio de Tipo de Contrato'), ('CAMBIO_MODALIDAD', 'Cambio de Modalidad'), ('RETIRO', 'Retiro'), ('REINTEGRO', 'Reintegro'), ('NUEVO_CONTRATO', 'Nuevo Contrato'), ('RENOVACION', 'Renovación de Contrato')], max_length=20)),
                ('campo', models.CharField(max_length=50)),
                ('valor_anterior', models.CharField(blank=True, max_length=500, null=True)),
                ('valor_nuevo', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_movimiento', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='api.datosempleado')),
            ],
            options={
                'db_table': 'movimiento_laboral',
                'ordering': ['-fecha_movimiento', '-created_at'],
            },
        ),
    ]
