# Generated by Django 4.2.30 on 2026-06-25 18:14

from django.db import migrations, models
import rbgct.sharepoint_storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_curso_creado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosacademicos',
            name='diploma',
            field=models.FileField(blank=True, null=True, storage=rbgct.sharepoint_storage.SharePointN8nStorage(), upload_to='datos_academicos/'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='pdf_contrato',
            field=models.FileField(blank=True, null=True, storage=rbgct.sharepoint_storage.SharePointN8nStorage(), upload_to='contratos/'),
        ),
        migrations.AlterField(
            model_name='contratorenovacion',
            name='pdf_renovacion',
            field=models.FileField(blank=True, null=True, storage=rbgct.sharepoint_storage.SharePointN8nStorage(), upload_to='contratos/renovaciones/'),
        ),
        migrations.AlterField(
            model_name='cursocontenido',
            name='archivo',
            field=models.FileField(blank=True, null=True, storage=rbgct.sharepoint_storage.SharePointN8nStorage(), upload_to='cursos/'),
        ),
        migrations.AlterField(
            model_name='movimientolaboral',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('CAMBIO_CARGO', 'Cambio de Cargo'), ('TRASLADO', 'Traslado de Área'), ('AJUSTE_SALARIAL', 'Ajuste Salarial'), ('CAMBIO_CONTRATO', 'Cambio de Tipo de Contrato'), ('CAMBIO_MODALIDAD', 'Cambio de Modalidad'), ('RETIRO', 'Retiro'), ('REINTEGRO', 'Reintegro'), ('NUEVO_CONTRATO', 'Nuevo Contrato'), ('RENOVACION', 'Renovación de Contrato'), ('ASCENSO', 'Ascenso'), ('DEGRADACION', 'Degradación')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reglamentoitem',
            name='archivo',
            field=models.FileField(blank=True, null=True, storage=rbgct.sharepoint_storage.SharePointN8nStorage(), upload_to='reglamento/'),
        ),
    ]
