# Generated by Django 4.2.30 on 2026-06-25 18:25

from django.db import migrations, models
import rbgct.sharepoint_storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_diploma_to_datos_academicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='pdf_contrato',
            field=models.FileField(blank=True, max_length=500, null=True, storage=rbgct.sharepoint_storage.SharePointN8nStorage(), upload_to='contratos/'),
        ),
        migrations.AlterField(
            model_name='contratorenovacion',
            name='pdf_renovacion',
            field=models.FileField(blank=True, max_length=500, null=True, storage=rbgct.sharepoint_storage.SharePointN8nStorage(), upload_to='contratos/renovaciones/'),
        ),
        migrations.AlterField(
            model_name='cursocontenido',
            name='archivo',
            field=models.FileField(blank=True, max_length=500, null=True, storage=rbgct.sharepoint_storage.SharePointN8nStorage(), upload_to='cursos/'),
        ),
        migrations.AlterField(
            model_name='datosacademicos',
            name='diploma',
            field=models.FileField(blank=True, max_length=500, null=True, storage=rbgct.sharepoint_storage.SharePointN8nStorage(), upload_to='datos_academicos/'),
        ),
        migrations.AlterField(
            model_name='reglamentoitem',
            name='archivo',
            field=models.FileField(blank=True, max_length=500, null=True, storage=rbgct.sharepoint_storage.SharePointN8nStorage(), upload_to='reglamento/'),
        ),
    ]
