# Generated by Django 4.2.30 on 2026-07-02 20:31

import core.mixins
from django.db import migrations, models
import django.db.models.deletion
import rbgct.sharepoint_storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS contratos;',
            reverse_sql='DROP SCHEMA IF EXISTS contratos CASCADE;',
        ),
        migrations.CreateModel(
            name='CajaCompensacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"contratos"."caja_compensacion"',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('termino_fijo', 'Término Fijo'), ('termino_indefinido', 'Término Indefinido'), ('obra_labor', 'Obra o Labor'), ('prestacion_servicios', 'Prestación de Servicios'), ('aprendizaje', 'Aprendizaje')], max_length=25)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('periodo_prueba_dias', models.IntegerField(default=0)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tipo_salario', models.CharField(choices=[('ordinario', 'Ordinario'), ('integral', 'Integral')], default='ordinario', max_length=10)),
                ('auxilio_transporte', models.BooleanField(default=True)),
                ('monto_auxilio_transporte', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bonificaciones', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('descripcion_bonificaciones', models.TextField(blank=True, null=True)),
                ('numero_contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('horas_semanales', models.IntegerField(blank=True, null=True)),
                ('forma_pago', models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal'), ('semanal', 'Semanal')], default='mensual', max_length=10)),
                ('jornada', models.CharField(choices=[('completa', 'Jornada Completa'), ('medio_tiempo', 'Medio Tiempo'), ('flexible', 'Jornada Flexible'), ('por_horas', 'Por Horas')], default='completa', max_length=15)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=10)),
                ('lugar_trabajo', models.CharField(blank=True, max_length=200, null=True)),
                ('pdf_contrato', models.FileField(blank=True, max_length=500, null=True, storage=rbgct.sharepoint_storage.SharePointN8nStorage(), upload_to='contratos/')),
                ('fecha_firma', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('VENCIDO', 'Vencido'), ('TERMINADO', 'Terminado'), ('RENOVADO', 'Renovado'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=15)),
                ('motivo_terminacion', models.CharField(blank=True, choices=[('renuncia', 'Renuncia Voluntaria'), ('despido_justa_causa', 'Despido con Justa Causa'), ('despido_sin_causa', 'Despido sin Justa Causa'), ('mutuo_acuerdo', 'Mutuo Acuerdo'), ('vencimiento', 'Vencimiento del Término'), ('obra_terminada', 'Terminación de la Obra'), ('muerte', 'Fallecimiento del Trabajador'), ('incapacidad', 'Incapacidad Permanente'), ('liquidacion_empresa', 'Liquidación de la Empresa')], max_length=25, null=True)),
                ('fecha_terminacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='empleados.datosempleado')),
            ],
            options={
                'db_table': '"contratos"."contrato"',
                'ordering': ['-created_at'],
            },
            bases=(core.mixins.UppercaseFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EntidadAFP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"contratos"."entidad_afp"',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EntidadARL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"contratos"."entidad_arl"',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EntidadEPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"contratos"."entidad_eps"',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContratoRenovacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_renovacion', models.DateField()),
                ('nueva_fecha_fin', models.DateField(blank=True, null=True)),
                ('nuevo_salario', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pdf_renovacion', models.FileField(blank=True, max_length=500, null=True, storage=rbgct.sharepoint_storage.SharePointN8nStorage(), upload_to='contratos/renovaciones/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renovaciones', to='contratos.contrato')),
            ],
            options={
                'db_table': '"contratos"."contrato_renovacion"',
                'ordering': ['-fecha_renovacion'],
            },
        ),
        migrations.CreateModel(
            name='AfiliacionSeguridadSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_afiliacion_eps', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_afiliacion_eps', models.DateField(blank=True, null=True)),
                ('numero_afiliacion_afp', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_afiliacion_afp', models.DateField(blank=True, null=True)),
                ('nivel_riesgo_arl', models.CharField(blank=True, choices=[('I', 'Nivel I — Riesgo Mínimo'), ('II', 'Nivel II — Riesgo Bajo'), ('III', 'Nivel III — Riesgo Medio'), ('IV', 'Nivel IV — Riesgo Alto'), ('V', 'Nivel V — Riesgo Máximo')], max_length=5, null=True)),
                ('numero_poliza_arl', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_afiliacion_arl', models.DateField(blank=True, null=True)),
                ('numero_afiliacion_caja', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_afiliacion_caja', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('afp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='afiliados', to='contratos.entidadafp')),
                ('arl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='afiliados', to='contratos.entidadarl')),
                ('caja_compensacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='afiliados', to='contratos.cajacompensacion')),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguridad_social', to='empleados.datosempleado')),
                ('eps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='afiliados', to='contratos.entidadeps')),
            ],
            options={
                'db_table': '"contratos"."afiliacion_seguridad_social"',
            },
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['empleado', 'estado'], name='contrato_emp_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='contrato',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ACTIVO')), fields=('empleado',), name='unique_contrato_activo_por_empleado'),
        ),
    ]
