# Generated by Django 4.2.30 on 2026-04-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosempleado',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
