# Generated by Django 4.2.30 on 2026-04-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_datosempleado_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosempleado',
            name='datos_completados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datosempleado',
            name='permitir_edicion_datos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datosempleado',
            name='primer_login',
            field=models.BooleanField(default=True),
        ),
    ]
