# Generated by Django 4.2.30 on 2026-04-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_datosempleado_sexo_datosempleado_tipo_sangre'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosempleado',
            name='apodo',
            field=models.CharField(blank=True, help_text='Nombre como desea ser llamado/a', max_length=50, null=True),
        ),
    ]
