# Generated by Django 4.2.30 on 2026-04-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_datosempleado_apodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosempleado',
            name='ultima_actividad',
            field=models.DateTimeField(blank=True, help_text='Última vez que el usuario estuvo activo', null=True),
        ),
    ]
