# Generated by Django 4.2.30 on 2026-04-17 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_datosempleado_ultima_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('recuperacion_password', 'Recuperación de Contraseña'), ('login_fallido', 'Intento de Login Fallido'), ('otro', 'Otro')], default='recuperacion_password', max_length=50)),
                ('email_solicitante', models.EmailField(max_length=255)),
                ('nombre_solicitante', models.CharField(blank=True, max_length=255, null=True)),
                ('rol_solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_alerta', models.CharField(choices=[('pendiente', 'Pendiente'), ('atendida', 'Atendida'), ('ignorada', 'Ignorada')], default='pendiente', max_length=50)),
                ('usuario_existe', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_atendidas', to='api.superadmin')),
                ('empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.datosempleado')),
            ],
            options={
                'db_table': 'alertas',
                'ordering': ['-fecha_creacion'],
                'managed': True,
            },
        ),
    ]
