# Generated by Django 4.2.30 on 2026-04-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alerta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglamentoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(blank=True, default='')),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reglamento_item',
                'ordering': ['orden'],
                'managed': True,
            },
        ),
    ]
