# Generated by Django 4.2.30 on 2026-04-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reglamentoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curso',
                'ordering': ['orden'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CursoContenido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('youtube', 'Video YouTube'), ('video', 'Video Propio'), ('documento', 'Documento'), ('texto', 'Texto/Artículo'), ('enlace', 'Enlace Externo'), ('cuestionario', 'Cuestionario')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='cursos/')),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='api.curso')),
            ],
            options={
                'db_table': 'curso_contenido',
                'ordering': ['orden'],
                'managed': True,
            },
        ),
    ]
