# Generated by Django 4.2.30 on 2026-04-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_curso_cursocontenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Fecha de ingreso a la empresa', null=True),
        ),
    ]
