# Generated by Django 4.2.30 on 2026-05-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_n8nlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='area',
            field=models.ForeignKey(blank=True, db_column='area_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.datosarea'),
        ),
        migrations.AddField(
            model_name='curso',
            name='empleado_asignado',
            field=models.ForeignKey(blank=True, db_column='empleado_asignado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_asignados', to='api.datosempleado'),
        ),
        migrations.AddField(
            model_name='curso',
            name='visibilidad',
            field=models.CharField(choices=[('todos', 'Todos'), ('area', 'Área Específica'), ('persona', 'Persona Específica')], default='todos', max_length=20),
        ),
        migrations.CreateModel(
            name='CursoHistorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curso_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('accion', models.CharField(choices=[('crear', 'Curso Creado'), ('editar', 'Curso Editado'), ('eliminar', 'Curso Eliminado'), ('agregar_contenido', 'Contenido Agregado'), ('eliminar_contenido', 'Contenido Eliminado')], max_length=20)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('usuario_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='api.curso')),
            ],
            options={
                'db_table': 'curso_historial',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
