# Generated by Django 4.2.30 on 2026-05-05 16:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_curso_area_curso_empleado_asignado_curso_visibilidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la API key', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('uso_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('permisos', models.JSONField(blank=True, default=dict, help_text="Permisos específicos: {'read': true, 'write': false, 'delete': false}")),
                ('ip_permitidas', models.JSONField(blank=True, default=list, help_text='Lista de IPs permitidas. Vacío = todas')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.superadmin')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_key',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
