# Generated by Django 4.2.30 on 2026-07-02 20:31

import core.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS tareas;',
            reverse_sql='DROP SCHEMA IF EXISTS tareas CASCADE;',
        ),
        migrations.CreateModel(
            name='TareasCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('area', models.ForeignKey(blank=True, db_column='id_area', null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.datosarea')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to='empleados.datosempleado')),
                ('empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.datosempleado')),
            ],
            options={
                'db_table': '"tareas"."tarea"',
            },
            bases=(core.mixins.UppercaseFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SugerenciaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugerencia', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('recibida', models.BooleanField(default=False)),
                ('fecha_recibida', models.DateTimeField(blank=True, null=True)),
                ('confirmacion_vista', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to='empleados.datosempleado')),
            ],
            options={
                'db_table': '"tareas"."sugerencia_empleado"',
                'ordering': ['-fecha_envio'],
                'indexes': [models.Index(fields=['recibida', 'fecha_envio'], name='tareas_sugerencia_recibida_idx'), models.Index(fields=['empleado', 'fecha_envio'], name='tareas_sugerencia_emp_idx')],
            },
        ),
    ]
