# Generated by Django 4.2.30 on 2026-07-02 20:31

import core.mixins
from django.db import migrations, models
import django.db.models.deletion
import rbgct.sharepoint_storage


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS empleados;',
            reverse_sql='DROP SCHEMA IF EXISTS empleados CASCADE;',
        ),
        migrations.CreateModel(
            name='DatosArea',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"empleados"."datos_area"',
            },
            bases=(core.mixins.UppercaseFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DatosCargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=100)),
                ('nivel', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"empleados"."datos_cargo"',
            },
            bases=(core.mixins.UppercaseFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DatosEmpleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('auth_id', models.UUIDField(blank=True, null=True)),
                ('correo_corporativo', models.EmailField(max_length=255, unique=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVO', 'Inactivo')], default='ACTIVA', max_length=20)),
                ('id_permisos', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Editor'), (3, 'Usuario')], default=3)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('primer_login', models.BooleanField(default=True)),
                ('datos_completados', models.BooleanField(default=False)),
                ('datos_persona_completados', models.BooleanField(default=False)),
                ('datos_academicos_completados', models.BooleanField(default=False)),
                ('permitir_edicion_datos', models.BooleanField(default=False)),
                ('acceso_sqf_clientes', models.BooleanField(default=False)),
                ('acceso_sqf_contratos', models.BooleanField(default=False)),
                ('acceso_sqf_facturacion', models.BooleanField(default=False)),
                ('acceso_sqf_auditoria', models.BooleanField(default=False)),
                ('es_encargado_cursos', models.BooleanField(default=False)),
                ('ultima_actividad', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, db_column='area_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.datosarea')),
                ('cargo', models.ForeignKey(blank=True, db_column='cargo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.datoscargo')),
            ],
            options={
                'db_table': '"empleados"."empleado"',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('apodo', models.CharField(blank=True, help_text='Nombre como desea ser llamado/a', max_length=50, null=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de Identidad')], default='CC', max_length=2)),
                ('numero_documento', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('lugar_expedicion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_expedicion', models.DateField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('ciudad_nacimiento', models.CharField(blank=True, max_length=150, null=True)),
                ('departamento_nacimiento', models.CharField(blank=True, max_length=150, null=True)),
                ('pais_nacimiento', models.CharField(blank=True, default='Colombia', max_length=100, null=True)),
                ('nacionalidad', models.CharField(blank=True, default='Colombiana', max_length=100, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('UL', 'Unión Libre'), ('D', 'Divorciado/a'), ('V', 'Viudo/a')], max_length=2, null=True)),
                ('estrato_socioeconomico', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tipo_vivienda', models.CharField(blank=True, choices=[('propia', 'Propia'), ('arrendada', 'Arrendada'), ('familiar', 'Familiar')], max_length=10, null=True)),
                ('tiene_discapacidad', models.BooleanField(default=False)),
                ('descripcion_discapacidad', models.TextField(blank=True, null=True)),
                ('tiene_hijos', models.BooleanField(default=False)),
                ('numero_hijos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tiene_vehiculo', models.BooleanField(default=False)),
                ('tipo_vehiculo', models.CharField(blank=True, choices=[('moto', 'Moto'), ('carro', 'Carro'), ('ambos', 'Moto y Carro')], max_length=10, null=True)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"empleados"."persona"',
            },
            bases=(core.mixins.UppercaseFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MovimientoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('CAMBIO_CARGO', 'Cambio de Cargo'), ('TRASLADO', 'Traslado de Área'), ('AJUSTE_SALARIAL', 'Ajuste Salarial'), ('CAMBIO_CONTRATO', 'Cambio de Tipo de Contrato'), ('CAMBIO_MODALIDAD', 'Cambio de Modalidad'), ('RETIRO', 'Retiro'), ('REINTEGRO', 'Reintegro'), ('NUEVO_CONTRATO', 'Nuevo Contrato'), ('RENOVACION', 'Renovación de Contrato'), ('ASCENSO', 'Ascenso'), ('DEGRADACION', 'Degradación')], max_length=20)),
                ('campo', models.CharField(max_length=50)),
                ('valor_anterior', models.CharField(blank=True, max_length=500, null=True)),
                ('valor_nuevo', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_movimiento', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='empleados.datosempleado')),
            ],
            options={
                'db_table': '"empleados"."movimiento_laboral"',
                'ordering': ['-fecha_movimiento', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datosempleado',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='empleados.persona'),
        ),
        migrations.CreateModel(
            name='DatosContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_personal', models.EmailField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('nombre_contacto_emergencia', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, null=True)),
                ('parentesco_emergencia', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacto', to='empleados.persona')),
            ],
            options={
                'db_table': '"empleados"."datos_contacto"',
            },
            bases=(core.mixins.UppercaseFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DatosAcademicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_educativo', models.CharField(choices=[('bachiller', 'Bachiller'), ('tecnico', 'Técnico'), ('tecnologo', 'Tecnólogo'), ('profesional', 'Profesional'), ('especializacion', 'Especialización'), ('maestria', 'Maestría'), ('doctorado', 'Doctorado'), ('otro', 'Otro')], max_length=20)),
                ('titulo_obtenido', models.CharField(max_length=255)),
                ('institucion', models.CharField(max_length=255)),
                ('ciudad_institucion', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_graduacion', models.DateField(blank=True, null=True)),
                ('en_curso', models.BooleanField(default=False)),
                ('graduado', models.BooleanField(default=True)),
                ('diploma', models.FileField(blank=True, max_length=500, null=True, storage=rbgct.sharepoint_storage.SharePointN8nStorage(), upload_to='datos_academicos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academicos', to='empleados.persona')),
            ],
            options={
                'db_table': '"empleados"."datos_academicos"',
                'ordering': ['-fecha_graduacion', '-fecha_inicio'],
            },
            bases=(core.mixins.UppercaseFieldsMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='datosempleado',
            index=models.Index(fields=['estado', 'ultima_actividad'], name='emp_estado_act_idx'),
        ),
        migrations.AddIndex(
            model_name='datosempleado',
            index=models.Index(fields=['ultima_actividad'], name='emp_ult_act_idx'),
        ),
        migrations.AddIndex(
            model_name='datosempleado',
            index=models.Index(fields=['estado'], name='emp_estado_idx'),
        ),
    ]
