# Generated by Django 4.2.30 on 2026-07-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_seed_areas_cargos'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='certificado_discapacidad',
            field=models.FileField(blank=True, null=True, upload_to='empleados/certificados_discapacidad/'),
        ),
    ]
