# Generated by Django 4.2.30 on 2026-07-07 13:40

import core.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_certificado_discapacidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_documento', models.CharField(choices=[('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], default='RC', max_length=2)),
                ('numero_identificacion', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='empleados.persona')),
            ],
            options={
                'db_table': '"empleados"."hijo"',
                'ordering': ['fecha_nacimiento'],
            },
            bases=(core.mixins.UppercaseFieldsMixin, models.Model),
        ),
    ]
