# Generated by Django 4.2.30 on 2026-07-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_add_hijo_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscontacto',
            name='departamento_residencia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='datoscontacto',
            name='municipio_residencia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='datoscontacto',
            name='pais_residencia',
            field=models.CharField(blank=True, default='Colombia', max_length=100, null=True),
        ),
    ]
