# Generated by Django 4.2.30 on 2026-07-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_add_ubicacion_residencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='datoscontacto',
            name='detalles_residencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
