# Generated by Django 4.2.30 on 2026-07-02 20:31

from django.db import migrations, models
import django.db.models.deletion
import rbgct.sharepoint_storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS formacion;',
            reverse_sql='DROP SCHEMA IF EXISTS formacion CASCADE;',
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('curso', 'Curso'), ('capacitacion', 'Capacitación')], default='curso', max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('visibilidad', models.CharField(choices=[('todos', 'Todos'), ('area', 'Área Específica'), ('persona', 'Persona Específica'), ('cargo', 'Cargo Específico')], default='todos', max_length=20)),
                ('nivel_cargo', models.IntegerField(blank=True, choices=[(0, 'Socio'), (1, 'Gerente Asociado'), (2, 'Senior'), (3, 'Líder de equipo'), (4, 'Analista')], null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('areas', models.ManyToManyField(blank=True, db_table='"formacion"."curso_area"', related_name='cursos_asignados', to='empleados.datosarea')),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_creados', to='empleados.datosempleado')),
                ('empleado_asignado', models.ForeignKey(blank=True, db_column='empleado_asignado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_asignados', to='empleados.datosempleado')),
            ],
            options={
                'db_table': '"formacion"."curso"',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CursoContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('youtube', 'Video YouTube'), ('video', 'Video Propio'), ('documento', 'Documento'), ('texto', 'Texto/Artículo'), ('enlace', 'Enlace Externo'), ('cuestionario', 'Cuestionario')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, max_length=500, null=True, storage=rbgct.sharepoint_storage.SharePointN8nStorage(), upload_to='cursos/')),
                ('orden', models.IntegerField(default=0)),
                ('max_intentos', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='formacion.curso')),
            ],
            options={
                'db_table': '"formacion"."curso_contenido"',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ReglamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField(blank=True, default='')),
                ('archivo', models.FileField(blank=True, max_length=500, null=True, storage=rbgct.sharepoint_storage.SharePointN8nStorage(), upload_to='reglamento/')),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '"formacion"."reglamento_item"',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PlanOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('nivel_cargo', models.IntegerField(blank=True, choices=[(0, 'Socio'), (1, 'Gerente Asociado'), (2, 'Senior'), (3, 'Líder de equipo'), (4, 'Analista')], null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_onboarding', to='empleados.datosarea')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_onboarding_creados', to='empleados.datosempleado')),
            ],
            options={
                'db_table': '"formacion"."plan_onboarding"',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CursoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('accion', models.CharField(choices=[('crear', 'Curso Creado'), ('editar', 'Curso Editado'), ('eliminar', 'Curso Eliminado'), ('agregar_contenido', 'Contenido Agregado'), ('eliminar_contenido', 'Contenido Eliminado')], max_length=20)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('usuario_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='formacion.curso')),
            ],
            options={
                'db_table': '"formacion"."curso_historial"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CuestionarioIntento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestas', models.JSONField(default=dict)),
                ('puntaje', models.FloatField()),
                ('aprobado', models.BooleanField()),
                ('num_intento', models.PositiveIntegerField(default=1)),
                ('tiempo_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='formacion.cursocontenido')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_cuestionarios', to='formacion.curso')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_cuestionarios', to='empleados.datosempleado')),
            ],
            options={
                'db_table': '"formacion"."cuestionario_intento"',
                'ordering': ['-fecha_intento'],
            },
        ),
        migrations.CreateModel(
            name='PasoOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('dias_limite', models.IntegerField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos_onboarding', to='formacion.curso')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='formacion.planonboarding')),
            ],
            options={
                'db_table': '"formacion"."paso_onboarding"',
                'ordering': ['orden'],
                'unique_together': {('plan', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='NotificacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='formacion.curso')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_cursos', to='empleados.datosempleado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_completados_notif', to='empleados.datosempleado')),
            ],
            options={
                'db_table': '"formacion"."notificacion_curso"',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['destinatario', 'leida'], name='formacion_notif_dest_leida_idx')],
                'unique_together': {('destinatario', 'empleado', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='ExclusionFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusiones', to='formacion.curso')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusiones_formacion', to='empleados.datosempleado')),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formaciones_excluidas_por', to='empleados.datosempleado')),
            ],
            options={
                'db_table': '"formacion"."exclusion_formacion"',
                'unique_together': {('empleado', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='CursoProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='formacion.cursocontenido')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='formacion.curso')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_cursos', to='empleados.datosempleado')),
            ],
            options={
                'db_table': '"formacion"."curso_progreso"',
                'ordering': ['-fecha_completado'],
                'unique_together': {('empleado', 'contenido')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboardings_asignados', to='empleados.datosempleado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_onboarding', to='empleados.datosempleado')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='formacion.planonboarding')),
            ],
            options={
                'db_table': '"formacion"."asignacion_onboarding"',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('empleado', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formaciones_asignadas', to='empleados.datosempleado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='formacion.curso')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_formacion', to='empleados.datosempleado')),
            ],
            options={
                'db_table': '"formacion"."asignacion_formacion"',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('empleado', 'curso')},
            },
        ),
    ]
