# Generated by Django 4.2.30 on 2026-05-11 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_seed_entidades_ss'),
    ]

    operations = [
        migrations.RunSQL('CREATE SCHEMA IF NOT EXISTS clientes;', reverse_sql='DROP SCHEMA IF EXISTS clientes CASCADE;'),
        migrations.CreateModel(
            name='EmpresaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('digito_verificacion', models.CharField(blank=True, max_length=1, null=True)),
                ('tipo_empresa', models.CharField(choices=[('microempresa', 'Microempresa'), ('pyme', 'PYME'), ('grande', 'Empresa Grande'), ('grupo_empresarial', 'Grupo Empresarial')], default='pyme', max_length=20)),
                ('tamano_empresa', models.CharField(blank=True, choices=[('micro', 'Micro (< 10 empleados)'), ('pequena', 'Pequeña (10–50 empleados)'), ('mediana', 'Mediana (51–200 empleados)'), ('grande', 'Grande (> 200 empleados)')], max_length=10, null=True)),
                ('actividad_economica', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcion_actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('regimen_tributario', models.CharField(blank=True, choices=[('simplificado', 'Régimen Simplificado'), ('comun', 'Régimen Común'), ('gran_contribuyente', 'Gran Contribuyente'), ('no_responsable', 'No Responsable de IVA'), ('especial', 'Régimen Especial')], max_length=20, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email_principal', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('prospecto', 'Prospecto'), ('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido'), ('retirado', 'Retirado')], default='activo', max_length=15)),
                ('nivel_riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto'), ('critico', 'Crítico')], default='bajo', max_length=10)),
                ('fecha_inicio_relacion', models.DateField(blank=True, null=True)),
                ('camara_comercio_numero', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa_matriz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiarias', to='clientes.empresacliente')),
            ],
            options={
                'db_table': '"clientes"."cli_empresa"',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='ServicioContratado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('valor_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('periodicidad', models.CharField(choices=[('mensual', 'Mensual'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('unico', 'Servicio Único')], default='mensual', max_length=15)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('terminado', 'Terminado')], default='activo', max_length=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios_clientes', to='api.datosarea')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='clientes.empresacliente')),
            ],
            options={
                'db_table': '"clientes"."cli_servicio"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('rut', 'RUT'), ('camara_comercio', 'Cámara de Comercio'), ('estado_financiero', 'Estado Financiero'), ('contrato_servicio', 'Contrato de Servicio'), ('certificado', 'Certificado'), ('declaracion', 'Declaración Tributaria'), ('poder', 'Poder / Autorización'), ('otro', 'Otro')], max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='clientes/documentos/')),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('vigente', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clientes.empresacliente')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_clientes_subidos', to='api.datosempleado')),
            ],
            options={
                'db_table': '"clientes"."cli_documento"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(choices=[('representante_legal', 'Representante Legal'), ('gerente', 'Gerente General'), ('contador', 'Contador'), ('auxiliar_contable', 'Auxiliar Contable'), ('abogado', 'Abogado'), ('tesoreria', 'Tesorería'), ('rrhh', 'RRHH'), ('revisor_fiscal', 'Revisor Fiscal'), ('otro', 'Otro')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.empresacliente')),
            ],
            options={
                'db_table': '"clientes"."cli_contacto"',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reunion', 'Reunión'), ('llamada', 'Llamada'), ('visita', 'Visita'), ('email', 'Correo'), ('entrega', 'Entrega de Documento'), ('novedad', 'Novedad'), ('otro', 'Otro')], max_length=15)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_registradas', to='api.datosempleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='clientes.empresacliente')),
            ],
            options={
                'db_table': '"clientes"."cli_bitacora"',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('responsable_principal', 'Responsable Principal'), ('gerente', 'Gerente'), ('senior', 'Senior'), ('analista', 'Analista/Asistente'), ('revisor', 'Revisor'), ('apoyo', 'Apoyo')], max_length=25)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes_asignados', to='api.datosempleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='clientes.empresacliente')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo', to='clientes.serviciocontratado')),
            ],
            options={
                'db_table': '"clientes"."cli_asignacion"',
                'ordering': ['-activo', 'rol'],
            },
        ),
        migrations.AddConstraint(
            model_name='asignacionequipo',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('empresa', 'empleado', 'servicio'), name='unique_asignacion_activa'),
        ),
    ]
