# Generated by Django 4.2.30 on 2026-05-13 18:58

from django.db import migrations, models
import rbgct.appwrite_storage


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_asignacion_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocliente',
            name='archivo',
            field=models.FileField(storage=rbgct.appwrite_storage.AppwriteFileStorage(), upload_to='clientes/documentos/'),
        ),
    ]
