# Generated by Django 4.2.30 on 2026-07-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_sqf_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudfacturacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
