# Generated by Django 4.2.30 on 2026-06-25 18:25

from django.db import migrations, models
import rbgct.sharepoint_storage


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_documentocliente_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentocliente',
            name='archivo',
            field=models.FileField(max_length=500, storage=rbgct.sharepoint_storage.SharePointN8nStorage(), upload_to='clientes/documentos/'),
        ),
    ]
