# Generated by Django 4.2.30 on 2026-07-15 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_add_detalles_residencia'),
        ('clientes', '0004_alter_solicitudfacturacion_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pausado', 'Pausado'), ('terminado', 'Terminado')], default='activo', max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipos', to='empleados.datosarea')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='clientes.empresacliente')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='clientes.serviciocontratado')),
            ],
            options={
                'db_table': '"clientes"."cli_equipo"',
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('gerente', 'Gerente'), ('senior', 'Senior'), ('lider_equipo', 'Líder de equipo'), ('semi_senior', 'Semi-senior'), ('analista', 'Analista'), ('asistente', 'Asistente'), ('revisor', 'Revisor'), ('apoyo', 'Apoyo')], max_length=25)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias_equipo', to='empleados.datosempleado')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='clientes.equipo')),
            ],
            options={
                'db_table': '"clientes"."cli_miembro_equipo"',
                'ordering': ['-activo', 'rol'],
            },
        ),
        migrations.AddConstraint(
            model_name='miembroequipo',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('equipo', 'empleado'), name='unique_miembro_activo_por_equipo'),
        ),
    ]
