# Generated by Django 4.2.30 on 2026-07-15 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_equipo_miembroequipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='equipo_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_equipos', to='clientes.equipo', verbose_name='equipo padre'),
        ),
    ]
