# Generated by Django 4.2.30 on 2026-07-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_equipo_equipo_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='especial',
            field=models.BooleanField(default=False, help_text='Contrato especial que no cumple la triarquía estándar (gerente, senior y analista/asistente).'),
        ),
    ]
