# Generated by Django 4.2.30 on 2026-07-02 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS sistema;',
            reverse_sql='DROP SCHEMA IF EXISTS sistema CASCADE;',
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('role', models.CharField(default='superadmin', max_length=50)),
                ('estado', models.CharField(default='ACTIVA', max_length=20)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': '"sistema"."superadmin"',
            },
        ),
        migrations.CreateModel(
            name='N8nLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('SUCCESS', 'Exitoso'), ('ERROR', 'Error')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('destinatario', models.EmailField(blank=True, max_length=255, null=True)),
                ('tipo_evento', models.CharField(blank=True, max_length=100, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"sistema"."n8n_log"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudesPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('atendida', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='empleados.datosempleado')),
            ],
            options={
                'db_table': '"sistema"."solicitudes_password"',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('uso_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('permisos', models.JSONField(blank=True, default=dict)),
                ('ip_permitidas', models.JSONField(blank=True, default=list)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': '"sistema"."api_key"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recuperacion_password', 'Recuperación de Contraseña'), ('login_fallido', 'Intento de Login Fallido'), ('otro', 'Otro')], default='recuperacion_password', max_length=50)),
                ('email_solicitante', models.EmailField(max_length=255)),
                ('nombre_solicitante', models.CharField(blank=True, max_length=255, null=True)),
                ('rol_solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_alerta', models.CharField(choices=[('pendiente', 'Pendiente'), ('atendida', 'Atendida'), ('ignorada', 'Ignorada')], default='pendiente', max_length=50)),
                ('usuario_existe', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_atendidas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(blank=True, db_column='id_empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.datosempleado')),
            ],
            options={
                'db_table': '"sistema"."alerta"',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['tipo', 'fecha_creacion'], name='sistema_alerta_tipo_fecha_idx'), models.Index(fields=['estado_alerta', 'fecha_creacion'], name='sis_alerta_estado_fecha_idx'), models.Index(fields=['email_solicitante'], name='sistema_alerta_email_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='superadmin',
            index=models.Index(fields=['last_login'], name='sis_sadm_last_login_idx'),
        ),
    ]
