# Generated by Django 4.2.30 on 2026-07-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_api_key_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(db_index=True, editable=False, max_length=64, unique=True),
        ),
    ]
